apiVersion: v2
name: api-gateway
description: A Helm chart for API Gateway microservice
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - api-gateway
  - microservice
  - nodejs
  - express

home: https://github.com/your-org/your-repo
sources:
  - https://github.com/your-org/your-repo

maintainers:
  - name: DevOps Team
    email: devops@yourdomain.com

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled