modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 201, 202]
      method: GET
      headers:
        Host: api.yourplatform.com
        User-Agent: "Blackbox Exporter"
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false

  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 201, 202]
      method: POST
      headers:
        Content-Type: application/json
        User-Agent: "Blackbox Exporter"
      body: '{"test": true}'

  http_auth_2xx:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 201]
      method: POST
      headers:
        Content-Type: application/json
        User-Agent: "Blackbox Exporter"
      body: '{"email": "test@example.com", "password": "testpassword"}'

  tcp_connect:
    prober: tcp
    timeout: 5s

  dns:
    prober: dns
    timeout: 5s
    dns:
      query_name: "api.yourplatform.com"
      query_type: "A"

  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"

  # Database connectivity check
  postgres_connect:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - expect: "^\\x00\\x00\\x00\\x08\\x04\\xd2\\x16/"

  # Redis connectivity check
  redis_connect:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - send: "*1\r\n$4\r\nPING\r\n"
        - expect: "^\\+PONG"

  # RabbitMQ management API check
  rabbitmq_management:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1"]
      valid_status_codes: [200]
      method: GET
      basic_auth:
        username: "admin"
        password: "admin"
      headers:
        User-Agent: "Blackbox Exporter"

  # Elasticsearch health check
  elasticsearch_health:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1"]
      valid_status_codes: [200]
      method: GET
      headers:
        User-Agent: "Blackbox Exporter"