version: '3.8'

services:
  redis-master:
    image: redis:7-alpine
    container_name: redis-master
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --replica-announce-ip redis-master
    volumes:
      - redis-master-data:/data
      - ./redis/redis-master.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster
    environment:
      - REDIS_REPLICATION_MODE=master

  redis-replica-1:
    image: redis:7-alpine
    container_name: redis-replica-1
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis-master 6379 --replica-announce-ip redis-replica-1
    volumes:
      - redis-replica-1-data:/data
    networks:
      - redis-cluster
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave

  redis-replica-2:
    image: redis:7-alpine
    container_name: redis-replica-2
    ports:
      - "6381:6379"
    command: redis-server --slaveof redis-master 6379 --replica-announce-ip redis-replica-2
    volumes:
      - redis-replica-2-data:/data
    networks:
      - redis-cluster
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave

  redis-sentinel-1:
    image: redis:7-alpine
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - redis-cluster
    depends_on:
      - redis-master

  redis-sentinel-2:
    image: redis:7-alpine
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - redis-cluster
    depends_on:
      - redis-master

  redis-sentinel-3:
    image: redis:7-alpine
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - redis-cluster
    depends_on:
      - redis-master

volumes:
  redis-master-data:
  redis-replica-1-data:
  redis-replica-2-data:

networks:
  redis-cluster:
    driver: bridge