groups:
  - name: service_alerts
    rules:
      # Service Down Alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on instance {{ $labels.instance }} has been down for more than 1 minute."

      # High Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for service {{ $labels.job }} for more than 5 minutes."

      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 1 second for service {{ $labels.job }}."

      # Database Connection Issues
      - alert: DatabaseConnectionHigh
        expr: db_connections_active / db_connections_max > 0.8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Database connection pool usage high"
          description: "Database connection pool usage is above 80% for {{ $labels.job }}."

      # Memory Usage High
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 90% on instance {{ $labels.instance }}."

      # CPU Usage High
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% on instance {{ $labels.instance }}."

      # Disk Space Low
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Disk space low"
          description: "Disk space is below 10% on instance {{ $labels.instance }} filesystem {{ $labels.mountpoint }}."

  - name: business_alerts
    rules:
      # Payment Service Specific
      - alert: PaymentFailureRateHigh
        expr: rate(payment_transactions_total{status="failed"}[5m]) / rate(payment_transactions_total[5m]) > 0.05
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: "High payment failure rate"
          description: "Payment failure rate is above 5% for more than 3 minutes."

      # Queue Length High
      - alert: MessageQueueLengthHigh
        expr: rabbitmq_queue_messages > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Message queue length high"
          description: "Queue {{ $labels.queue }} has more than 1000 messages for 5 minutes."

      # Authentication Service
      - alert: AuthenticationFailureRateHigh
        expr: rate(auth_attempts_total{status="failed"}[5m]) / rate(auth_attempts_total[5m]) > 0.2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failure rate is above 20% for more than 5 minutes."

      # File Service
      - alert: FileUploadFailureRateHigh
        expr: rate(file_uploads_total{status="failed"}[5m]) / rate(file_uploads_total[5m]) > 0.1
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High file upload failure rate"
          description: "File upload failure rate is above 10% for more than 3 minutes."