apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    environment: {{ .Values.app.environment }}
    {{- if .Values.istio.enabled }}
    istio-injection: enabled
    {{- end }}
    {{- include "multi-service-platform.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- if ne .Values.app.environment "production" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}-staging
  labels:
    name: {{ .Values.namespace }}-staging
    environment: staging
    {{- if .Values.istio.enabled }}
    istio-injection: enabled
    {{- end }}
    {{- include "multi-service-platform.labels" . | nindent 4 }}
{{- end }}