{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "multi-service-platform.fullname" . }}-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multi-service-platform.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  {{- if .Values.networkPolicy.ingress.enabled }}
  - Ingress
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  - Egress
  {{- end }}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
  # Allow ingress from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 3000
    - protocol: TCP
      port: 3001
    - protocol: TCP
      port: 3002
    - protocol: TCP
      port: 3003
    - protocol: TCP
      port: 3004
    - protocol: TCP
      port: 3005
    - protocol: TCP
      port: 3006
    - protocol: TCP
      port: 3007
    - protocol: TCP
      port: 3008
    - protocol: TCP
      port: 3009
  # Allow inter-service communication within namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    ports:
    - protocol: TCP
      port: 3000
    - protocol: TCP
      port: 3001
    - protocol: TCP
      port: 3002
    - protocol: TCP
      port: 3003
    - protocol: TCP
      port: 3004
    - protocol: TCP
      port: 3005
    - protocol: TCP
      port: 3006
    - protocol: TCP
      port: 3007
    - protocol: TCP
      port: 3008
    - protocol: TCP
      port: 3009
  # Allow monitoring from monitoring namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8080  # metrics port
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow access to databases
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    ports:
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 6379  # Redis
    - protocol: TCP
      port: 5672  # RabbitMQ
    - protocol: TCP
      port: 9200  # Elasticsearch
  # Allow HTTPS to external services
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
  {{- end }}
---
{{- if .Values.networkPolicy.enabled }}
# Separate policy for database access
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "multi-service-platform.fullname" . }}-database-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multi-service-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
  - Ingress
  ingress:
  # Only allow access from application services
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "multi-service-platform.name" . }}
    ports:
    - protocol: TCP
      port: 5432
---
# Redis access policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "multi-service-platform.fullname" . }}-redis-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multi-service-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
  - Ingress
  ingress:
  # Only allow access from application services
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "multi-service-platform.name" . }}
    ports:
    - protocol: TCP
      port: 6379
---
# RabbitMQ access policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "multi-service-platform.fullname" . }}-rabbitmq-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multi-service-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: rabbitmq
  policyTypes:
  - Ingress
  ingress:
  # Only allow access from application services
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "multi-service-platform.name" . }}
    ports:
    - protocol: TCP
      port: 5672
    - protocol: TCP
      port: 15672  # Management UI
{{- end }}
{{- end }}