apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "multi-service-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # JWT Secrets
  JWT_SECRET: {{ .Values.security.jwtSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.security.jwtRefreshSecret | quote }}
  
  # Encryption Key
  ENCRYPTION_KEY: {{ .Values.security.encryptionKey | quote }}
  
  # Database Passwords
  {{- if .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  {{- end }}
  {{- if .Values.rabbitmq.enabled }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password | quote }}
  {{- end }}
  
  # External Service API Keys
  {{- if .Values.externalServices.stripe.enabled }}
  STRIPE_SECRET_KEY: {{ .Values.externalServices.stripe.secretKey | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.externalServices.stripe.webhookSecret | quote }}
  {{- end }}
  {{- if .Values.externalServices.sendgrid.enabled }}
  SENDGRID_API_KEY: {{ .Values.externalServices.sendgrid.apiKey | quote }}
  {{- end }}
  {{- if .Values.externalServices.twilio.enabled }}
  TWILIO_ACCOUNT_SID: {{ .Values.externalServices.twilio.accountSid | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.externalServices.twilio.authToken | quote }}
  {{- end }}
  
  # AWS Credentials
  {{- if .Values.externalServices.aws.enabled }}
  AWS_ACCESS_KEY_ID: {{ .Values.externalServices.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.externalServices.aws.secretAccessKey | quote }}
  {{- end }}
  
  # OAuth Secrets
  {{- if .Values.oauth.google.enabled }}
  GOOGLE_CLIENT_ID: {{ .Values.oauth.google.clientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.oauth.google.clientSecret | quote }}
  {{- end }}
  {{- if .Values.oauth.facebook.enabled }}
  FACEBOOK_APP_ID: {{ .Values.oauth.facebook.appId | quote }}
  FACEBOOK_APP_SECRET: {{ .Values.oauth.facebook.appSecret | quote }}
  {{- end }}
  {{- if .Values.oauth.apple.enabled }}
  APPLE_CLIENT_ID: {{ .Values.oauth.apple.clientId | quote }}
  APPLE_TEAM_ID: {{ .Values.oauth.apple.teamId | quote }}
  APPLE_KEY_ID: {{ .Values.oauth.apple.keyId | quote }}
  APPLE_PRIVATE_KEY: {{ .Values.oauth.apple.privateKey | quote }}
  {{- end }}
{{- if .Values.global.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "multi-service-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.imagePullSecrets | first | b64enc }}
{{- end }}