{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "multi-service-platform.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "multi-service-platform" }}
  labels:
    {{- include "multi-service-platform.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}

{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "multi-service-platform.fullname" . }}-role
  namespace: {{ .Values.namespace | default "multi-service-platform" }}
  labels:
    {{- include "multi-service-platform.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
{{- if .Values.serviceMonitor.enabled }}
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "multi-service-platform.fullname" . }}-rolebinding
  namespace: {{ .Values.namespace | default "multi-service-platform" }}
  labels:
    {{- include "multi-service-platform.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "multi-service-platform.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "multi-service-platform" }}
roleRef:
  kind: Role
  name: {{ include "multi-service-platform.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io

{{- if .Values.rbac.clusterRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "multi-service-platform.fullname" . }}-cluster-role
  labels:
    {{- include "multi-service-platform.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "multi-service-platform.fullname" . }}-cluster-rolebinding
  labels:
    {{- include "multi-service-platform.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "multi-service-platform.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "multi-service-platform" }}
roleRef:
  kind: ClusterRole
  name: {{ include "multi-service-platform.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}