global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@yourplatform.com'
  smtp_auth_username: 'alerts@yourplatform.com'
  smtp_auth_password: 'your-app-password'
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    # Critical alerts go to PagerDuty and Slack immediately
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
      continue: true

    # Infrastructure alerts
    - match:
        category: infrastructure
      receiver: 'infrastructure-team'
      group_interval: 5m
      repeat_interval: 30m

    # Database alerts
    - match:
        category: database
      receiver: 'database-team'
      group_interval: 5m
      repeat_interval: 30m

    # Security alerts
    - match:
        category: security
      receiver: 'security-team'
      group_wait: 0s
      repeat_interval: 15m

    # Business alerts
    - match:
        category: business
      receiver: 'business-team'
      group_interval: 15m
      repeat_interval: 2h

    # Performance alerts
    - match:
        category: performance
      receiver: 'performance-team'
      group_interval: 10m
      repeat_interval: 1h

    # Service-specific routing
    - match:
        service: payment
      receiver: 'payment-team'
      group_interval: 2m
      repeat_interval: 15m

    - match:
        service: authentication
      receiver: 'auth-team'
      group_interval: 5m
      repeat_interval: 30m

    # Maintenance window - suppress non-critical alerts
    - match:
        severity: warning
      receiver: 'maintenance-suppression'
      active_time_intervals:
        - maintenance-window

# Inhibition rules
inhibit_rules:
  # Inhibit warning alerts if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Inhibit service alerts if node is down
  - source_match:
      alertname: 'NodeDown'
    target_match_re:
      alertname: '.*Service.*'
    equal: ['instance']

  # Inhibit high error rate if service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match:
      alertname: 'HighErrorRate'
    equal: ['job']

# Time intervals for maintenance windows
time_intervals:
  - name: maintenance-window
    time_intervals:
      - times:
        - start_time: '02:00'
          end_time: '04:00'
        weekdays: ['sunday']
        months: ['1:12']

# Receivers configuration
receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'devops@yourplatform.com'
        subject: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  - name: 'critical-alerts'
    pagerduty_configs:
      - routing_key: 'your-pagerduty-integration-key'
        description: '{{ .GroupLabels.alertname }}: {{ .Annotations.summary }}'
        details:
          firing: '{{ .Alerts.Firing | len }}'
          resolved: '{{ .Alerts.Resolved | len }}'
          alertname: '{{ .GroupLabels.alertname }}'
        links:
          - href: '{{ .Annotations.runbook_url }}'
            text: 'Runbook'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/CRITICAL/WEBHOOK'
        channel: '#critical-alerts'
        title: 'CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
        color: 'danger'

  - name: 'infrastructure-team'
    email_configs:
      - to: 'infrastructure@yourplatform.com'
        subject: '[INFRA] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#infrastructure'
        title: 'Infrastructure Alert: {{ .GroupLabels.alertname }}'
        color: 'warning'

  - name: 'database-team'
    email_configs:
      - to: 'database@yourplatform.com'
        subject: '[DB] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#database'
        title: 'Database Alert: {{ .GroupLabels.alertname }}'
        color: 'warning'

  - name: 'security-team'
    email_configs:
      - to: 'security@yourplatform.com'
        subject: '[SECURITY] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#security'
        title: 'Security Alert: {{ .GroupLabels.alertname }}'
        color: 'danger'
    pagerduty_configs:
      - routing_key: 'security-pagerduty-key'
        description: 'Security Alert: {{ .Annotations.summary }}'

  - name: 'business-team'
    email_configs:
      - to: 'business@yourplatform.com'
        subject: '[BUSINESS] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#business-alerts'
        title: 'Business Alert: {{ .GroupLabels.alertname }}'
        color: 'warning'

  - name: 'performance-team'
    email_configs:
      - to: 'performance@yourplatform.com'
        subject: '[PERF] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#performance'
        title: 'Performance Alert: {{ .GroupLabels.alertname }}'
        color: 'warning'

  - name: 'payment-team'
    email_configs:
      - to: 'payment-team@yourplatform.com'
        subject: '[PAYMENT] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#payment-alerts'
        title: 'Payment Alert: {{ .GroupLabels.alertname }}'
        color: 'danger'
    pagerduty_configs:
      - routing_key: 'payment-pagerduty-key'
        description: 'Payment Alert: {{ .Annotations.summary }}'

  - name: 'auth-team'
    email_configs:
      - to: 'auth-team@yourplatform.com'
        subject: '[AUTH] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#auth-alerts'
        title: 'Authentication Alert: {{ .GroupLabels.alertname }}'
        color: 'warning'

  - name: 'maintenance-suppression'
    # Empty receiver to suppress alerts during maintenance