apiVersion: v1
kind: Namespace
metadata:
  name: multi-service-platform
  labels:
    name: multi-service-platform
    environment: production
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: multi-service-platform-staging
  labels:
    name: multi-service-platform-staging
    environment: staging
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
    environment: production