apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: multi-service-platform
  labels:
    app.kubernetes.io/name: multi-service-platform
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # JWT Secrets
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
  JWT_REFRESH_SECRET: "your-super-secret-refresh-key-change-in-production"
  
  # Encryption Key
  ENCRYPTION_KEY: "your-32-character-encryption-key-here"
  
  # Database Passwords
  POSTGRES_PASSWORD: "changeme-in-production"
  REDIS_PASSWORD: "changeme-in-production"
  RABBITMQ_PASSWORD: "changeme-in-production"
  
  # External Service API Keys
  STRIPE_SECRET_KEY: "sk_test_your_stripe_secret_key"
  STRIPE_WEBHOOK_SECRET: "whsec_your_webhook_secret"
  SENDGRID_API_KEY: "SG.your_sendgrid_api_key"
  TWILIO_ACCOUNT_SID: "your_twilio_account_sid"
  TWILIO_AUTH_TOKEN: "your_twilio_auth_token"
  
  # AWS Credentials
  AWS_ACCESS_KEY_ID: "your_aws_access_key"
  AWS_SECRET_ACCESS_KEY: "your_aws_secret_key"
  
  # OAuth Secrets
  GOOGLE_CLIENT_SECRET: "your_google_client_secret"
  FACEBOOK_APP_SECRET: "your_facebook_app_secret"
  APPLE_PRIVATE_KEY: "your_apple_private_key"
  
  # Admin Credentials
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "changeme-in-production"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: multi-service-platform
  labels:
    app.kubernetes.io/name: multi-service-platform
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==