# Taxi Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-service
  namespace: multi-service-platform
  labels:
    app: taxi-service
    app.kubernetes.io/name: taxi-service
    app.kubernetes.io/component: business
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: taxi-service
  template:
    metadata:
      labels:
        app: taxi-service
        app.kubernetes.io/name: taxi-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3004"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: multi-service-platform-sa
      containers:
      - name: taxi-service
        image: multi-service-platform/taxi-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3004
          name: http
          protocol: TCP
        env:
        - name: PORT
          value: "3004"
        - name: SERVICE_NAME
          value: "taxi-service"
        envFrom:
        - configMapRef:
            name: platform-config
        - secretRef:
            name: platform-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: taxi-service
  namespace: multi-service-platform
  labels:
    app: taxi-service
    app.kubernetes.io/name: taxi-service
    app.kubernetes.io/component: business
spec:
  selector:
    app: taxi-service
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: taxi-service-hpa
  namespace: multi-service-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taxi-service
  minReplicas: 2
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
# Hotel Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  namespace: multi-service-platform
  labels:
    app: hotel-service
    app.kubernetes.io/name: hotel-service
    app.kubernetes.io/component: business
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
        app.kubernetes.io/name: hotel-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3005"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: multi-service-platform-sa
      containers:
      - name: hotel-service
        image: multi-service-platform/hotel-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3005
          name: http
        env:
        - name: PORT
          value: "3005"
        - name: SERVICE_NAME
          value: "hotel-service"
        envFrom:
        - configMapRef:
            name: platform-config
        - secretRef:
            name: platform-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
  namespace: multi-service-platform
  labels:
    app: hotel-service
    app.kubernetes.io/name: hotel-service
    app.kubernetes.io/component: business
spec:
  selector:
    app: hotel-service
  ports:
  - port: 3005
    targetPort: 3005
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hotel-service-hpa
  namespace: multi-service-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hotel-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70