# Advertisement Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advertisement-service
  namespace: multi-service-platform
  labels:
    app: advertisement-service
    app.kubernetes.io/name: advertisement-service
    app.kubernetes.io/component: business
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: advertisement-service
  template:
    metadata:
      labels:
        app: advertisement-service
        app.kubernetes.io/name: advertisement-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3006"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: multi-service-platform-sa
      containers:
      - name: advertisement-service
        image: multi-service-platform/advertisement-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3006
          name: http
        env:
        - name: PORT
          value: "3006"
        - name: SERVICE_NAME
          value: "advertisement-service"
        envFrom:
        - configMapRef:
            name: platform-config
        - secretRef:
            name: platform-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3006
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3006
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: advertisement-service
  namespace: multi-service-platform
  labels:
    app: advertisement-service
    app.kubernetes.io/name: advertisement-service
    app.kubernetes.io/component: business
spec:
  selector:
    app: advertisement-service
  ports:
  - port: 3006
    targetPort: 3006
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: advertisement-service-hpa
  namespace: multi-service-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: advertisement-service
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
# Notification Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: multi-service-platform
  labels:
    app: notification-service
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: platform
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        app.kubernetes.io/name: notification-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3007"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: multi-service-platform-sa
      containers:
      - name: notification-service
        image: multi-service-platform/notification-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3007
          name: http
        env:
        - name: PORT
          value: "3007"
        - name: SERVICE_NAME
          value: "notification-service"
        envFrom:
        - configMapRef:
            name: platform-config
        - secretRef:
            name: platform-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3007
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3007
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: multi-service-platform
  labels:
    app: notification-service
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: platform
spec:
  selector:
    app: notification-service
  ports:
  - port: 3007
    targetPort: 3007
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service-hpa
  namespace: multi-service-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70