# File Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: multi-service-platform
  labels:
    app: file-service
    app.kubernetes.io/name: file-service
    app.kubernetes.io/component: platform
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
        app.kubernetes.io/name: file-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3008"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: multi-service-platform-sa
      containers:
      - name: file-service
        image: multi-service-platform/file-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3008
          name: http
        env:
        - name: PORT
          value: "3008"
        - name: SERVICE_NAME
          value: "file-service"
        envFrom:
        - configMapRef:
            name: platform-config
        - secretRef:
            name: platform-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3008
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3008
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: uploads
          mountPath: /uploads
      volumes:
      - name: tmp
        emptyDir: {}
      - name: uploads
        persistentVolumeClaim:
          claimName: file-service-pvc
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: file-service
  namespace: multi-service-platform
  labels:
    app: file-service
    app.kubernetes.io/name: file-service
    app.kubernetes.io/component: platform
spec:
  selector:
    app: file-service
  ports:
  - port: 3008
    targetPort: 3008
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-service-pvc
  namespace: multi-service-platform
  labels:
    app: file-service
    app.kubernetes.io/name: file-service
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: file-service-hpa
  namespace: multi-service-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: file-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
# Search Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: multi-service-platform
  labels:
    app: search-service
    app.kubernetes.io/name: search-service
    app.kubernetes.io/component: platform
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
        app.kubernetes.io/name: search-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3009"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: multi-service-platform-sa
      containers:
      - name: search-service
        image: multi-service-platform/search-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3009
          name: http
        env:
        - name: PORT
          value: "3009"
        - name: SERVICE_NAME
          value: "search-service"
        envFrom:
        - configMapRef:
            name: platform-config
        - secretRef:
            name: platform-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3009
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3009
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: search-data
          mountPath: /data
      volumes:
      - name: tmp
        emptyDir: {}
      - name: search-data
        persistentVolumeClaim:
          claimName: search-service-pvc
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: multi-service-platform
  labels:
    app: search-service
    app.kubernetes.io/name: search-service
    app.kubernetes.io/component: platform
spec:
  selector:
    app: search-service
  ports:
  - port: 3009
    targetPort: 3009
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-service-pvc
  namespace: multi-service-platform
  labels:
    app: search-service
    app.kubernetes.io/name: search-service
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: search-service-hpa
  namespace: multi-service-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70