# Pod Disruption Budgets for High Availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: multi-service-platform
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: authentication-service-pdb
  namespace: multi-service-platform
  labels:
    app: authentication-service
    app.kubernetes.io/name: authentication-service
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: authentication-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ecommerce-service-pdb
  namespace: multi-service-platform
  labels:
    app: ecommerce-service
    app.kubernetes.io/name: ecommerce-service
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: ecommerce-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-service-pdb
  namespace: multi-service-platform
  labels:
    app: payment-service
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 2  # Critical service - always keep 2 running
  selector:
    matchLabels:
      app: payment-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: taxi-service-pdb
  namespace: multi-service-platform
  labels:
    app: taxi-service
    app.kubernetes.io/name: taxi-service
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: taxi-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hotel-service-pdb
  namespace: multi-service-platform
  labels:
    app: hotel-service
    app.kubernetes.io/name: hotel-service
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: hotel-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-service-pdb
  namespace: multi-service-platform
  labels:
    app: notification-service
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: notification-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: file-service-pdb
  namespace: multi-service-platform
  labels:
    app: file-service
    app.kubernetes.io/name: file-service
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: file-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: search-service-pdb
  namespace: multi-service-platform
  labels:
    app: search-service
    app.kubernetes.io/name: search-service
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: search-service