apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: multi-service-platform
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  API_GATEWAY_URL: "http://api-gateway-service:3000"
  ELASTICSEARCH_HOST: "elasticsearch-service"
  ELASTICSEARCH_PORT: "9200"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config-staging
  namespace: multi-service-platform-staging
data:
  NODE_ENV: "staging"
  LOG_LEVEL: "debug"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  API_GATEWAY_URL: "http://api-gateway-service:3000"
  ELASTICSEARCH_HOST: "elasticsearch-service"
  ELASTICSEARCH_PORT: "9200"