apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: multi-service-platform
  labels:
    app: search-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
        version: v1
    spec:
      containers:
      - name: search-service
        image: multi-service-platform/search-service:latest
        ports:
        - containerPort: 3009
        env:
        - name: PORT
          value: "3009"
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/search_db"
        envFrom:
        - configMapRef:
            name: platform-config
        - secretRef:
            name: platform-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3009
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3009
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: multi-service-platform
  labels:
    app: search-service
spec:
  selector:
    app: search-service
  ports:
  - port: 3009
    targetPort: 3009
    protocol: TCP
  type: ClusterIP