export enum EventType {
  AD_POSTED = 'AD_POSTED',
  ORDER_CREATED = 'ORDER_CREATED',
  RIDE_REQUESTED = 'RIDE_REQUESTED',
  DRIVER_ACCEPTED = 'DRIVER_ACCEPTED',
  PAYMENT_PROCESSED = 'PAYMENT_PROCESSED'
}
